on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: timburgan
          password: ${{ secrets.GHCR_TIMBURGAN_PAT }}
      - name: push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/doh:latest
            docker.pkg.github.com/${{ github.repository }}/doh:${{ github.sha }}
