on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: timburgan
          password: ${{ secrets.GHCR_TIMBURGAN_PAT }}
          repository: ${{ github.repository }}/doh
          tag_with_ref: true
          context: .
          file: ./Dockerfile
