on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
        
        # https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md
      - uses: crazy-max/ghaction-setup-containerd@v1
      
      - name: login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: timburgan
          password: ${{ secrets.GHCR_TIMBURGAN_PAT }}
      - name: push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          tags: |
            docker.pkg.github.com/${{ github.repository }}/meh:latest
            docker.pkg.github.com/${{ github.repository }}/meh:${{ github.sha }}
          outputs: type=oci,dest=/tmp/image.tar
      - name: Import image in containerd
        run: sudo ctr i import --base-name docker.pkg.github.com/${{ github.repository }}/meh --digests --all-platforms /tmp/image.tar
      - name: Push image with containerd
        run: sudo ctr --debug i push --user "timburgan:${{ secrets.GHCR_TIMBURGAN_PAT }}" docker.pkg.github.com/${{ github.repository }}/meh:latest
            
