on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: timburgan
          password: ${{ secrets.GHCR_TIMBURGAN_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/meh:latest
            docker.pkg.github.com/${{ github.repository }}/meh:${{ github.sha }}
            
