# This file contains job definitions to run static tests over global ops config YAMLs.
# The result of the test is used in the automerge job defined in global-ops-config-automerge.yaml
name: Global Operational Config Tests
on:
  pull_request_target:
    branches: [ main ]
    paths: folder/**
env:
  PR_NUM: ${{ github.event.pull_request.number }}
jobs:
  test-operational-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch PR and checkout merged commit
        run: |
          echo "Fetching PR merge branch"
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin pull/$PR_NUM/merge:pr-merge-branch
          echo "Checking PR merge branch"
          git checkout pr-merge-branch
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install pytest pyyaml
      - name: Run tests
        run: |
          cd folder && pytest -v --color=yes
